### ISSUE TITLE
Section 1.3: animations are incorrect

### ISSUE THREAD

**Issue by ickerwx** [securedorg/securedorg.github.io#3]
Hi Amanda,

thank you very much for making this available and spending your time to create this workshop.

I was skimming over the first section to see if this would be something for a friend of mine who is very interested in learning about reverse engineering, and I noticed that in section 1.3 the animations seem to be incorrect.

helloworld.gif:
* `mov [esp+10h+var_10], eax` should move eax right at the top of the stack, as var_10 is -10 so the destination would be `esp+10-10 -> esp`. Since you show esp to be at the top of the rectangle, next to "Local variables", this should be the location of eax.
* Depending on what your goal is for this picture I would actually remove this var_10 thing entirely, it is probably pretty confusing for somebody who's dealing with this for the first time. My knowledge of how disassemblers work is pretty limited, but to me this seems to be an IDA Pro artifact.

FunctionCall.gif
* The order of the parameters on the stack is not correct. You show that the first thing that is pushed is eax, and every subsequent push moves eax (and everything else that was pushed before) further down the stack, but this is not what it should actually look like since push automatically decreases esp as well.

I also think that slowing down the animations might make following them easier.

**Comment by securedorg** [comment]
I agree with you in helloworld.gif it should be esp+10-10 and I will update this. However I do not agree with the second comment for FunctionCall.gif based on the debugging and a diagram illustrating this concept. The lower addresses are at the top and higher address are at the bottom.

![screenflow](https://cloud.githubusercontent.com/assets/19986532/24589668/3d2c8820-1793-11e7-8676-ac2085582a22.gif)

![w19l1](https://cloud.githubusercontent.com/assets/19986532/24589686/8a28209e-1793-11e7-9437-e9069189f68a.png)

**Comment by ickerwx** [comment]
I'm sorry that I have to be so persistent, but I think either I failed to explain myself or the image is really confusing and could do with a little more context to make it clearer what you want to say.

My understanding is that we are looking at the stack frame of the caller, meaning the function that is going to call `RegOpenKeyExA`. It is not really clear to me because you are showing Return Address, Saved EBP and Local Variables that look like the beginning of the stack frame for `RegOpenKeyExA`, but these do not yet exist when the animation starts. After each push you reference each argument relative to ebp, so after you pushed eax it is placed at `ebp + 8`, and after all arguments are pushed eax is at `ebp + 24`. This implies, since ebp is supposed to be static, that the location of eax (and all other pushed values after) change their location with each push, which is not correct as you can see in the debugger screenshot you posted: the addresses of course stay the same.

The only time your image is actually correct is after the function prologue for `RegOpenKeyExA`, when EBP actually is the base pointer for the callee's stack frame. Since the upper half of the purple box seems to reference EBP as the base pointer of the callee's stack frame even though we are clearly still in the caller's stack frame at the start of the animation (and the code never even shows the callee), the image is probably a little hard to understand for someone who is new to all this.

So after thinking about this a little more I guess I kind of agree with you that the image is not wrong per se, but it is lacking a lot of context to make it clear what the viewer is looking at.

**Comment by securedorg** [comment]
Ahh this explains a lot. Yeah I mix frames together. The main point I wanted to get across is conceptually how will the data look in the debugger. Even some assembly courses at universities in the states don't explain this concept very well.
