### ISSUE TITLE
malware in section 4

### ISSUE THREAD

**Issue by f-fly2** [securedorg/securedorg.github.io#4]
Hi

Which malware is what i am downloading in section 4? I assume it is not harmful and is just for training pourposes, isnt it?

Thanks

**Comment by securedorg** [comment]
Nah it's not harmful. It exhibits real malware techniques but you'll have to find the secret at the end.

**Comment by f-fly2** [comment]
Hi

Sorry i didnt read this. Virustotal reports this as a generic ransomware... Not 100% sure if i should download it?

https://virustotal.com/en/file/a635f37c16fc05e554a6c7b3f696e47e8eaf3531407cac27e357851cb710e615/analysis/1492487889/

**Comment by securedorg** [comment]
LMAO. Well I made it malware-y enough. I have the source code.
