### ISSUE TITLE
RE101: VM issue

### ISSUE THREAD

**Issue by Quantomicus** [securedorg/securedorg.github.io#46]
I have downloaded both .ova files, tried starting the victim VM up and it threw me to the login screen. There exists no `victim` user account, only one called IE user and the password isn't the one provided. After checking the MD5 hashes, both of them are right. I'd appreciate some help over this matter. Thanks in advance.

**Comment by securedorg** [comment]
Please select “switch user” and manually sign into victim

**Comment by Quantomicus** [comment]
Already tried that. No dice.

**Comment by securedorg** [comment]
![issue](https://user-images.githubusercontent.com/19986532/34644292-7eda36ba-f2e8-11e7-9b06-3a3b98f549d9.gif)
Please check this gif file.

**Comment by Quantomicus** [comment]
Hm. I reimported the file and now it works. Weird. Thanks anyway.
