### ISSUE TITLE
RE102: Sample got flagged as infected on GDrive, cannot be downloaded

### ISSUE THREAD

**Issue by cookieburra** [securedorg/securedorg.github.io#47]
Hello!
It seems like the sample for RE102 has been flagged as infected, and thus is no longer available for download. Screenshot below:

![Google Drive's message](https://user-images.githubusercontent.com/3727187/35480857-2147bc5c-0418-11e8-8038-6d378e689e6a.png)

**Comment by securedorg** [comment]
It should be downloadable now.

**Comment by cookieburra** [comment]
I’m afraid the problem still exists.

**Comment by securedorg** [comment]
Updated to RE102Malware.7z, please try that.

**Comment by cookieburra** [comment]
That worked. Thanks a ton! Closing the issue.
