### ISSUE TITLE
RE101 Lab 3 Dynamic Analysis

### ISSUE THREAD

**Issue by adimenia** [securedorg/securedorg.github.io#7]
Hey When setting up a breakpoint XorDecode function and running the program using F9 it dosent hit the breakpoint for some reason. the program executes until it exits.
![image](https://user-images.githubusercontent.com/5006200/27996438-99789b56-64ea-11e7-8b3c-abb34f85d542.png)
and here the program terminates without hitting the breakpoint
![image](https://user-images.githubusercontent.com/5006200/27996449-b921f33a-64ea-11e7-874d-b134218265fb.png)
any ideas?

**Comment by securedorg** [comment]
Did you set the breakpoints on the loop jge instruction? You need to make sure you are in the xordecode function and then set the breakpoint.

**Comment by adimenia** [comment]
okay there is something weird, i have rebased the program to 76FD1000 (which the base address the program loads in the debugger) and im able to locate the function at 76FD1530 in IDA. but in the Debugger this offset is still in ntdll.dll code. which is probably why im not able to break on XorDecode as the debugger and IDA are not in sync. any idea why im experiencing this?

**Comment by adimenia** [comment]
Okay Figured it out :)
